-- App acessa o Postgres via Prisma (role owner, ignora RLS). Habilitar RLS sem policies
-- BLOQUEIA acesso pela API pública (anon/publishable via PostgREST), fechando a exposição.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Offer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OfferType" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PageFormat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Template" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TemplatePage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OfferFrame" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FrameStyle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tabloid" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TabloidPage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TabloidOffer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TabloidVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TabloidElement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Review" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReviewParticipant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReviewAction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Export" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LayoutRun" ENABLE ROW LEVEL SECURITY;
